### ISSUE TITLE
Warning: touch(): Utime failed: Operation not permitted after installation

### ISSUE THREAD

**Issue by leac** [gtn/exaport#16]
Hi 

After installing the block, I get 2 errors of this kind:

> Warning: touch(): Utime failed: Operation not permitted in /blocks/exaport/build/developermode.php on line 130

> Warning: touch(): Utime failed: Operation not permitted in /blocks/exaport/build/developermode.php on line 144

What should I do?

**Comment by leac** [comment]
I set all files in this block's folder to 644 and that seams to have solved the problem:
`find . -type f -exec chmod 0644 {} \;`

**Comment by sammarshallou** [comment]
Note: Making files in your dirroot (PHP source) writable by the Apache user introduces a security risk. You should set up your web server so that the Apache user does not own, and cannot create or write, any PHP files or folders. See https://docs.moodle.org/35/en/Security_recommendations#Running_Moodle_on_a_dedicated_server

**Comment by leac** [comment]
@sammarshallou  Thank you for your note. 
According to that link, 644 should be set on files, which is what I did. And Apache is not the owner.
